version: '3.8'
networks:
  network-db:
    driver: bridge
    labels:
      - network-db
  network-app:
    driver: bridge
    labels:
      - network-app
services:
  mysql-db:
    container_name: mysql-db
    image: mysql:8.3.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-scripts/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=123455
    networks:
      - network-db
  node-app:
    build:
      dockerfile: ./Dockerfile
    container_name: node_app
    restart: always
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=123455
      - MYSQL_HOST=mysql-db
    networks:
      - network-db
      - network-app
    depends_on:
      - mysql-db
  proxy-nginx:
    build:
      dockerfile: ./proxy-nginx/Dockerfile
    container_name: proxy-nginx
    ports:
      - "8080:80"
    volumes:
      - ./proxy-nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - network-app
    depends_on:
      - node-app
