version: '3.8'

services:
  mysql-db:
    container_name: mysql_db
    image: mysql:8.3.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=123455
    ports:
      - '3306:3306'
  node-app:
    build: 
      dockerfile: ./Dockerfile
    container_name: node_app
    restart: always
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=123455
      - MYSQL_HOST=mysql-db
    ports:
      - '3000:8080'
networks:
  bridge:
  host: